# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mapreduce.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'mapreduce.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fmapreduce.proto\x12\tmapreduce\"\x1a\n\nMapRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"&\n\x08KeyValue\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\".\n\x08MapReply\x12\"\n\x05pairs\x18\x01 \x03(\x0b\x32\x13.mapreduce.KeyValue\",\n\rReduceRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x0e\n\x06values\x18\x02 \x03(\t\")\n\x0bReduceReply\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t2\x81\x01\n\x10MapReduceService\x12\x31\n\x03Map\x12\x15.mapreduce.MapRequest\x1a\x13.mapreduce.MapReply\x12:\n\x06Reduce\x12\x18.mapreduce.ReduceRequest\x1a\x16.mapreduce.ReduceReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mapreduce_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MAPREQUEST']._serialized_start=30
  _globals['_MAPREQUEST']._serialized_end=56
  _globals['_KEYVALUE']._serialized_start=58
  _globals['_KEYVALUE']._serialized_end=96
  _globals['_MAPREPLY']._serialized_start=98
  _globals['_MAPREPLY']._serialized_end=144
  _globals['_REDUCEREQUEST']._serialized_start=146
  _globals['_REDUCEREQUEST']._serialized_end=190
  _globals['_REDUCEREPLY']._serialized_start=192
  _globals['_REDUCEREPLY']._serialized_end=233
  _globals['_MAPREDUCESERVICE']._serialized_start=236
  _globals['_MAPREDUCESERVICE']._serialized_end=365
# @@protoc_insertion_point(module_scope)
